export const SEARCH_QUERY_UPDATED = 'SEARCH_UPDATED';
export const SEARCH_REQUEST_CREATED = 'SEARCH_REQUEST_CREATED';
export const SEARCH_REQUEST_SUCCESS = 'SEARCH_REQUEST_SUCCESS';
export const SEARCH_REQUEST_FAILURE = 'SEARCH_REQUEST_FAILURE';